application: ovraiment
version: dev
runtime: python
api_version: 1

handlers:
- url: /et.*
  login: required
  secure: always
  script: ovraiment.py

- url: /c2dm/.*
  login: required
  secure: always
  script: c2dm.py
